//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class huiyirichen
    {
        public int id { get; set; }
        public int areaid { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string areastr { get; set; }
        public System.DateTime addtime { get; set; }
    }
}
