//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRMDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBConnection : DbContext
    {
        public DBConnection()
            : base("name=DBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<province> province { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<huiyijiangyi> huiyijiangyi { get; set; }
        public virtual DbSet<huiyijianjie> huiyijianjie { get; set; }
        public virtual DbSet<huiyirichen> huiyirichen { get; set; }
        public virtual DbSet<huiyirichen_c> huiyirichen_c { get; set; }
        public virtual DbSet<jiangzhejieshao> jiangzhejieshao { get; set; }
        public virtual DbSet<jiaotong> jiaotong { get; set; }
        public virtual DbSet<jiaotong_c> jiaotong_c { get; set; }
        public virtual DbSet<lianxiwomen> lianxiwomen { get; set; }
        public virtual DbSet<shipin> shipin { get; set; }
        public virtual DbSet<zhinan> zhinan { get; set; }
    }
}
