//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string openid { get; set; }
        public int provinceid { get; set; }
        public string provincename { get; set; }
        public int cityid { get; set; }
        public string cityname { get; set; }
        public int areaid { get; set; }
        public string name { get; set; }
        public string telnum { get; set; }
        public string workaddr { get; set; }
        public string department { get; set; }
        public Nullable<int> age { get; set; }
        public string techtitle { get; set; }
        public System.DateTime addtime { get; set; }
    }
}
